language: php

php:
    - 7.1

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: SYMFONY_VERSION='4.1.*'
        - php: 7.2
          env: SYMFONY_VERSION='4.1.*'

before_install:
    - phpenv config-add travis.php.ini
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;

install:
    - composer update --prefer-dist

script:
    - vendor/bin/phpunit
    - vendor/bin/php-cs-fixer fix --dry-run -v --using-cache=null src
